### PR TITLE
Adding tests for pio inquire functions

### PR DESCRIPTION
**Pull request by jayeshkrishna**
Adding a test for some pio (variable, dim, att) inquire functions.
More tests are required for better coverage, but this is a
start.

### CODE REVIEW

**Comment by jayeshkrishna** [comment]
In most cases the return values are checked for correctness (PIO_TF_PASSERT*) but we could add more checks like making sure that all ranks get the same var/dim ids.

**Comment by jayeshkrishna** [comment]
I will soon add a feature to the testing framework to check if all tasks have the same value for a variable. Then it would be easy to add these checks.

**Comment by jedwards4b** [comment]
I don't see this in develop yet.

**Comment by jayeshkrishna** [comment]
I am holding off my merge to develop because when I merge my branch to develop it also brings in update_yellowstone_gnu-2 (part of PR #347). It looks like PR #347 was not merged to develop.

**Comment by jayeshkrishna** [comment]
Just verified that the change in PR #347 is on develop. Will merge this branch soon.

**Comment by jayeshkrishna** [comment]
This PR should be ready to merge to master (passes on cdash)

**Pull request merged**
