### PR TITLE
fixes pnetcdf BYTE read for USE_VARD=OFF

### PR DESCRIPTION
**Pull request by jedwards4b**
Using MPI_BYTE datatype from pnetcdf was broken, this is a fix when USE_VARD=OFF.  I have opened an issue in pnetcdf for USE_VARD=ON.   https://github.com/Parallel-NetCDF/PnetCDF/issues/76

### CODE REVIEW

**Comment by edwardhartnett** [comment]
I had trouble with the byte type in pnetcdf, and most of the tests don't try to test byte on pnetcdf, IIRC. I found what I thought was a bug in pnetcdf, and filed an issue. I don't know if it's been fixed since then...

**Comment by jedwards4b** [comment]
@edwardhartnett I don't see any issue related to the BYTE type in the pnetcdf repo except the one I just opened. Do you know where it is?

**Comment by jedwards4b** [comment]
The response to the issue in the pnetcdf repo is that we should use MPI_SIGNED_CHAR instead of MPI_BYTE.  Testing this now, it may make this PR moot.

**Comment by jedwards4b** [comment]
@edwardhartnett where do I need to look to try turning the BYTE type tests back on for pnetcdf?

**Comment by jedwards4b** [comment]
Closed, https://github.com/NCAR/ParallelIO/pull/1883 is a better fix.

**Pull request closed without merging**
