### PR TITLE
removed nc_set_log_level_2_, updated docs

### LINKED ISSUE #353: PIO library needs to build even if netcdf was built without logging
When I build against a netcdf that does not have logging enabled, I get this error:

/usr/local/bin/mpifort    -g  CMakeFiles/pio_unit_test.dir/basic_tests.F90.o CMakeFiles/pio_unit_test.dir/driver.F90.o CMakeFiles/pio_unit_test.dir/global_vars.F90.o CMakeFiles/pio_unit_test.dir/ncdf_tests.F90.o CMakeFiles/pio_unit_test.dir/nc_set_log_level2.c.o  -o pio_unit_test  ../../src/flib/libpiof.a ../../src/clib/libpioc.a /usr/local/netcdf-c-4.4.1/lib/libnetcdf.so ../../src/gptl/libgptl.a /usr/local/netcdf-fortran-4.4.3/lib/libnetcdff.so /usr/local/pnetcdf-1.7.0/lib/libpnetcdf.a -Wl,-rpath,/usr/local/netcdf-c-4.4.1/lib:/usr/local/netcdf-fortran-4.4.3/lib 
CMakeFiles/pio_unit_test.dir/nc_set_log_level2.c.o: In function `nc_set_log_level2_':
/home/ed/pio3/ParallelIO/tests/unit/nc_set_log_level2.c:7: undefined reference to `nc_set_log_level'
collect2: error: ld returned 1 exit status
tests/unit/CMakeFiles/pio_unit_test.dir/build.make:204: recipe for target 'tests/unit/pio_unit_test' failed
make[3]: *** [tests/unit/pio_unit_test] Error 1
make[3]: Leaving directory '/home/ed/pio3/ParallelIO/build'
CMakeFiles/Makefile2:1796: recipe for target 'tests/unit/CMakeFiles/pio_unit_test.dir/all' failed
make[2]: *** [tests/unit/CMakeFiles/pio_unit_test.dir/all] Error 2
make[2]: Leaving directory '/home/ed/pio3/ParallelIO/build'
CMakeFiles/Makefile2:1033: recipe for target 'CMakeFiles/tests.dir/rule' failed
make[1]: *** [CMakeFiles/tests.dir/rule] Error 2
make[1]: Leaving directory '/home/ed/pio3/ParallelIO/build'
Makefile:550: recipe for target 'tests' failed
make: *** [tests] Error 2
[ed@localhost build]$

### PR DESCRIPTION
**Pull request by edhartnett**
Fix #353.

Also updated documentation on build to match recent releases of libraries.

### CODE REVIEW

**Comment by edhartnett** [comment]
OK, just realized what I am doing here, which is taking away the ability of the fortran tests to set the nc_log_level.

However, now we have pio_set_log_level() for fortran which sets the PIO logging. Do you also need the netCDF logging?

If so, why not use the fortran function nf_set_log_level()?

**Comment by jedwards4b** [comment]
One of the goals of converting this library to c was to get away from reliance on the underlying fortran interfaces.

**Comment by edhartnett** [comment]
OK, I agree that it does not make sense for PIO to use any part of the netcdf fortran API. Unfortunately it does include netcdf.inc somewhere, which it should not.

So I guess you don't want to use nf_set_log_level().

I am going to modify PIOc_set_log_level() so that if nc_set_log_level() is available, it will also be set, to whatever log level you set in PIOc_set_log_level - 3.

So if you sent PIOc_set_log_level(3), then you will get lots of PIO logging, but still no netcdf logging. But if you call PIOc_set_log_level(4) you will also set the netcdf logging level to 1 and start to get some logging from the netcdf library.

What do you think? I will do that as a separate PR from this though...

**Comment by edhartnett** [comment]
I have merged this with develop branch for testing.

**Comment by jedwards4b** [comment]
Sounds good, thanks.

**Pull request merged**
