### PR TITLE
Make async mode writes really async

### LINKED ISSUE #1427: shall we really go async?
Our async mode is not really async.

When writing data, ultimately PIOc_put_vars_tc() is called. In PIOc_put_vars_tc, the following code appears at the bottom:
```
    /* Broadcast and check the return code. */
    if ((mpierr = MPI_Bcast(&ierr, 1, MPI_INT, ios->ioroot, ios->my_comm)))
        return check_mpi(NULL, file, mpierr, __FILE__, __LINE__);
    if (ierr)
        return check_netcdf(file, ierr, __FILE__, __LINE__);
    LOG((2, "PIOc_put_vars_tc bcast netcdf return code %d complete", ierr));
```

So what is happening is that the compute nodes actually wait for the data to be written, and then they get the return code.

But if we blow off the return code MPI_Bcast, then the compute processor can return from the function after transfering data to the IO processor. As soon as the MPI data transfer is complete, the compute processor can get a return code of 0 and continue on it's merry way, while the I/O processor continues to do the disk write.

This is easily accomplished in code. The above code block is commented out, and only the IO processor checks the return code of the disk write. If it fails, well, then we are all screwed, because the compute processor has continued to process, but aside from that, making this change should allow true async operation.

When I make this change and run on jet, I see no difference in write performance, but this is expected. The write does not happen faster, but the compute processor gets to compute while data is being written.

@jedwards4b can you ponder this change and tell me if you think it's OK? I will submit a PR this morning...

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #1427.

No longer make compute processors wait for return code from data writes, allowing them to continue processing while writes are happening.

### CODE REVIEW

**Comment by edhartnett** [comment]
I agree, but what is sane in this context?

The compute task has already moved on. What should the IO task do with the error?

**Comment by jedwards4b** [comment]
I guess we have to assume errors are fatal.   We don't have a mechanism for the io tasks to signal the compute tasks but maybe we can report the error the next time compute tasks make contact with the io tasks?

**Comment by edhartnett** [comment]
I was thinking that as well. Essentially that's what will happen if we do nothing. The IO tasks will error and exit. The next time the compute tasks try to contact, they will time out or error out because the IO communicator is gone.

I will write some tests for this, and also to examine the proposed new error mode (#1424).

**Comment by edhartnett** [comment]
Assuming errors are fatal is fine. I doubt any model code in existence tries to do anything other than exit with a netcdf error code. I'm just happy if they bother to check the error code.

For netcdf errors, what can the model do, other than throw up its hands and exit?

**Comment by gold2718** [comment]
I assume you mean read and write errors. There is lots of code that handles errors from inquiry functions.

**Comment by jedwards4b** [comment]
yes, read and write errors - inquire functions are by necessity not async.

**Pull request merged**
