### PR TITLE
got test working with new darray type checking

### LINKED ISSUE #1100: Async tests coverage is zero for PIOc_setframe() and PIOc_advanceframe()
I thought at least one of the existing tests would have used these functions...

### LINKED ISSUE #1108: test_darray_async_many is not being tested
In tests/cunit/CMakeLists.txt, test_darray_async_many actually executes test_darray_async
```
    add_mpi_test(test_darray_async
      EXECUTABLE ${CMAKE_CURRENT_BINARY_DIR}/test_darray_async
      NUMPROCS ${AT_LEAST_FOUR_TASKS}
      TIMEOUT ${DEFAULT_TEST_TIMEOUT})
    add_mpi_test(test_darray_async_many
      EXECUTABLE ${CMAKE_CURRENT_BINARY_DIR}/test_darray_async
      NUMPROCS ${AT_LEAST_FOUR_TASKS}
      TIMEOUT ${DEFAULT_TEST_TIMEOUT}) 
```

PS, test_darray_async_many did not pass on anlworkstation (time out with errors):
```
1 Error -33 in tests/cunit/test_darray_async_many.c, line 411
2 Error -33 in tests/cunit/test_darray_async_many.c, line 411
3 Error -33 in tests/cunit/test_darray_async_many.c, line 411
```
Please make sure it can pass on your local machine before adding it to CTest.

### PR DESCRIPTION
**Pull request by edhartnett**
Turned on test that wasn't running (thanks @dqwu).

Fixes #1108.
Fixes #1100.

I will merge to develop for testing.

### CODE REVIEW

**Comment by dqwu** [comment]
This test still fails on anlworkstation. I will take a look later, do not merge it to master at this time.

**Comment by edhartnett** [comment]
Found and fixed an incorrectly sized array. Interesting that the address sanitizer failed to catch this one.

Also interesting that this memory error did not make any cdash build fail, but it did fail on one of my jenkins builds.

I guess the lesson is that eternal vigilance is the price of leak-free C libraries.

**Comment by dqwu** [comment]
@edhartnett 
I found the same bug with Address Sanitizer. It did not report any errors on original test. Strangely, when I modified some test code, it reported that:
[1760, 1772) 'dimid' <== Memory access at offset 1772 overflows this variable

We can see the size of dimid is 12 bytes (3 integers), which should be updated to 16 bytes (4 integers).

With your fix this test now pass on anlworkstation.

**Comment by dqwu** [comment]
@edhartnett 
"Also interesting that this memory error did not make any cdash build fail"
It looks that in "http://my.cdash.org/index.php?project=PIO", all of the builds are not using CMake option PIO_USE_MALLOC=ON. Therefore, this test is not run by those builds.

**Pull request merged**
