### PR TITLE
Add cmake check for nc logging

### PR DESCRIPTION
**Pull request by jedwards4b**
Add a test to see if netcdf has logging enabled.   This sets  NetCDF_C_LOGGING_ENABLED
the variable is not yet used.

### CODE REVIEW

**Comment by jedwards4b** [comment]
I've merged this to develop for testing

**Comment by jedwards4b** [comment]
Fixes #355

**Comment by jedwards4b** [comment]
Should be okay now - try again.

**Comment by edhartnett** [comment]
OK, you sadly overmerged by changes away. Both of us working on the same branch was not a good idea!

I will merge this code to master right now, and then continue on another branch.

**Comment by jedwards4b** [comment]
Is the develop branch messed up too?

**Comment by edhartnett** [comment]
I will try and fix develop...

**Pull request merged**
