### PR TITLE
auto-formatting code and tests

### PR DESCRIPTION
**Pull request by edhartnett**
Formatting changes only.

I thought I had done this to all files before, but I missed some. Simple indent-region, untabify, and delete-trailing-whitespace,

No code changes in this PR, just white space stuff.

### CODE REVIEW

**Comment by jayeshkrishna** [comment]
Do we have a script that formats the code (that a developer could run on the source code tree before checking it in) as per coding-style guidelines?

**Comment by edhartnett** [comment]
Nope! ;-) I just use an emacs macro to do it all.

**Comment by jayeshkrishna** [comment]
Are we done formatting all the C source files as per the new coding style?

**Comment by edhartnett** [comment]
Yes.

**Comment by jayeshkrishna** [comment]
Thanks !

**Pull request merged**
