### PR TITLE
Added test for cases where unlimited dimension is in use

### LINKED ISSUE #441: Tests for some untested functions in pioc.c
PIOc_get_numiotasks()
PIOc_advanceframe()
PIOc_get_iorank()
PIOc_set_hint()
PIOc_iam_iotask()
PIOc_iotask_rank()
PIOc_iotype_available()

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #441.

Test code only in this PR.

I added a new C test, test_pioc_unlim.c, for tests of decompotion/darray/etc which involve an unlimited dimension. (Existing tests don't have unlimited dim).

This allowed testing of the PIOc_setframe() and PIOc_advanceframe(), and that's what this PR does, but future PRs will add aditional tests to test_pioc_unlim.c.

I will merge to develop for testing.

### CODE REVIEW

**Comment by dqwu** [comment]
test_pioc_unlim failed AddressSanitizer check on develop build. Please hold this PR before we fix the issue.

**Comment by dqwu** [comment]
@edhartnett 
On one side, in test_shared.c, run_test_main() has the following code:
```
/* Run tests without async feature. */
if ((ret = test_no_async2(my_rank, num_flavors, flavor, test_comm, max_ntasks,
                          dim_len[1], dim_len[2])))
```
This means that dim_len should have an array length of at least 3 (accesses index 2).

On the other side, in test_pioc_unlim.c, the array length is 2:
```
#define NDIM 2
...
int dim_len[NDIM] = {NC_UNLIMITED, X_DIM_LEN};
```

Please find out which side is wrong.

**Comment by edhartnett** [comment]
Stand by, I will fix.

**Comment by dqwu** [comment]
@edhartnett
Please merge the fix to develop branch for testing, thanks.

**Comment by edhartnett** [comment]
I have fixed and merged fix to develop branch.

**Comment by dqwu** [comment]
Originally failed develop builds passed now.

**Comment by edhartnett** [comment]
Awesome, thanks. I will merge.

**Pull request merged**
