### PR TITLE
fix leak

### LINKED ISSUE #681: 21 Fortran tests failed memory leak check
This issue is caused by PR #680, which is reproducible in both develop and master branches.

[Root cause of the leaks]
In flush_buffer(), pio_darray_int.c, the code is updated by the PR such that if PIOc_write_darray_multi() returns an error, flush_buffer() will return that error, without executing the following clean up code.
```
/* If there are any variables in this buffer... */
if (wmb->validvars > 0)
{
    /* Write any data in the buffer. */
    if ((ret = PIOc_write_darray_multi(ncid, wmb->vid,  wmb->ioid, wmb->validvars,
                                       wmb->arraylen, wmb->data, wmb->frame,
                                       wmb->fillvalue, flushtodisk)))
        return pio_err(NULL, file, ret, __FILE__, __LINE__);

    wmb->validvars = 0;

    /* Release the list of variable IDs. */
    brel(wmb->vid);
    wmb->vid = NULL;
    ...
}
```

[Code that triggers the leaks]
On the other hand, in PIOc_write_darray_multi(), pio_darray.c, the code is updated by the PR to check returned value from flush_output_buffer(). For the 21 failed Fortran tests, flush_output_buffer() does return an error code (e.g. PIO_EBADID), which is then returned by PIOc_write_darray_multi().
```
/* Flush data to disk. */
if (file->iotype == PIO_IOTYPE_PNETCDF)
    if ((ierr = flush_output_buffer(file, flushtodisk, 0)))
        return pio_err(ios, file, ierr, __FILE__, __LINE__);
```

[How to fix]
We should make sure that the clean up code is executed even if PIOc_write_darray_multi() fails.

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #681.

### CODE REVIEW

**Comment by jayeshkrishna** [comment]
Do the valgrind tests (as discussed in #681) pass now?

**Comment by dqwu** [comment]
@jayeshkrishna 
This fix can make both Valgrind check and LSan check local builds pass. Jenkins builds can confirm this later once it is merged to develop branch.

**Comment by jayeshkrishna** [comment]
It is a good idea for the developer to try it out (to make sure the leaks are fixed).

**Comment by dqwu** [comment]
@edhartnett 
You can merge it to the develop branch now for testing.

**Comment by edhartnett** [comment]
Merged to develop.

**Pull request merged**
