### PR TITLE
update to work with newer perl versions

### PR DESCRIPTION
**Pull request by jedwards4b**
Fixes issue #174

### CODE REVIEW

**Comment by jayeshkrishna** [comment]
Is there a way to get rid of the "extra space changes" (so that we clearly see what changed)?

**Comment by jedwards4b** [comment]
git diff -w master
diff --git a/tests/general/util/pio_tf_f90gen.pl b/tests/general/util/pio_tf_f90gen.pl
index 005fa37..8cb913c 100755
--- a/tests/general/util/pio_tf_f90gen.pl
+++ b/tests/general/util/pio_tf_f90gen.pl
@@ -483,8 +483,8 @@ sub transform_src
 # Returns 1 => if a generic template func is found, 0 otherwise
 sub find_gen_templ_funcs
 {
-  my($_, $ref_templ_typenames) = @_;
-  if(/^\s*PIO_TF_TEMPLATE\s*<(.*)>.*$/s){
+  my($str, $ref_templ_typenames) = @_;
+  if($str =~ /^\s*PIO_TF_TEMPLATE\s*<(.*)>.*$/s){
     if($1 eq ''){
       print "Error parsing template code, Check syntax of PIO_TF_TEMPLATE...\n";
       return 0;

**Comment by edhartnett** [comment]
Looks good! Thanks for the quick update. Merge as soon as you like and I will take a new branch.

**Comment by rljacob** [comment]
We've talked before about mixing white-space changes with more purposeful changes.  Please don't.  If your emacs does it for you, turn that off.

**Pull request merged**
