### PR TITLE
reindented, untabified, and deleted trailing whitespace

### PR DESCRIPTION
**Pull request by edhartnett**
A good suggestion from the meeting is that reformatting be applied to the entire codebase, without any other changes, as its own pull request.

That is what this is. In emacs I opened each file and ran the following commands:
M-x indent-region (for the whole file)
M-x untabify
M-x delete-trailing-whitespace

So there are no actual code changes. Just a lot of whitespace changes.

### CODE REVIEW

**Comment by rljacob** [comment]
Before merging this, we should make sure no one has any branches in progress that they are ready to merge.  This needs to be a sync point in development.

**Comment by rljacob** [comment]
No branches that are touching the same files, that is.

**Comment by edhartnett** [comment]
@rljacob do you have such a branch out?

How about you @jayeshkrishna?

**Comment by jayeshkrishna** [comment]
I don't think I have any branches that touches these sources. PR #132 should have all the changes (only touches the fortran tests and the testing framework - tests/general/*) I need to get merged now.

**Comment by rljacob** [comment]
I also don't have any branches outstanding.

**Pull request merged**
