### PR TITLE
fully remove pio_use_malloc macro

### LINKED ISSUE #1760: Test #29: test_simple not running in 2_5_2 release
I'm running the regression-tests in the 2_5_2 release and am seeing this failiure:
```
      Start 29: test_simple
29/98 Test #29: test_simple ........................***Failed    0.72 sec
--------------------------------------------------------------------------
mpiexec was unable to launch the specified application as it could not access
or execute an executable:

Executable: /gpfs/fs1/SHARE/Utils/PIO/2_5_2/PGI-20.9_OpenMPI-4.0.5_NetCDF-F-4.5.3_HDF5-1.12.0_UCX-1.9.0/build/tests/cunit/test_simple
Node: prm-dgx-04

while attempting to start process rank 0.
--------------------------------------------------------------------------
4 total processes failed to start
```
Looking through the build log, it looks like the other test-cases are being built but not this one.
I don't see any messages indicating any build failure, I just don't see any lines indicating that it's trying to build it.

### PR DESCRIPTION
**Pull request by jedwards4b**
Some tests were not being run because the macro had not full been removed
Fixes #1760

### CODE REVIEW

**Comment by edwardhartnett** [comment]
Seems like you changes the indent from 4 to 3 in these code files. Can you not do that? It's kind of inconvenient. Is there some reason 3 is better than 4?

**Comment by jedwards4b** [comment]
Not sure what happened, I did not intentionally do that, I will fix.

**Comment by jedwards4b** [comment]
Apparently my editor replaced some spaces with tabs, should be fixed now.

**Review by edwardhartnett — APPROVED** [review]
Duh. How did I miss all this?

**Pull request merged**
