### PR TITLE
Changes to support PIO1 namelists in PIO2 in cesm2_0_alpha03

### PR DESCRIPTION
**Pull request by Katetc**

### CODE REVIEW

**Comment by jedwards4b** [comment]
This will allow the code to compile and is what I had to do in the cesm repo, but what I really want in this PR is to implement the functionality of these controls.

**Comment by jayeshkrishna** [comment]
@Katetc / @jedwards4b : I am really interested in this work and am willing to put effort to implement these controls, if you are ok with it. 
@Katetc : If you have already started working on this item please go ahead (and ignore this comment).

**Comment by Katetc** [comment]
Hi @jayeshkrishna , that's fine if you want to take over the PIO1 namelist support in PIO2. Thanks for your help!!

**Comment by jayeshkrishna** [comment]
@Katec : Glad to help. Can you go ahead and merge this PR to master? This would get the compilation going as you noted above and then I will branch off the master to implement these features.

**Pull request merged**
