### PR TITLE
Update license to Apache 2

### PR DESCRIPTION
**Pull request by climbfuji**
Submitting this PR for your consideration.

The existing `COPYRIGHT` file refers to a GPL license, which is incompatible for use with many licenses (Apache 2, Adobe CC0, ...) used at NCAR and partner organizations that require ParallelIO. I believe that the existing ParallelIO license is conflicting with the licenses under which MPAS and ESMF are released - please correct me if I am wrong.

This PR removes the old `COPYRIGHT` file and adds a boilerplate Apache 2 `LICENSE` file instead.

### CODE REVIEW

**Comment by gold2718** [comment]
I am not sure CESM's use of ParallelIO (PIO) violates the letter or spirit of the GPL license because CESM does not contain PIO. To use CESM, you need a PIO library but it is not included except by reference (i.e., no PIO code is copied into CESM or into any of its components).

Other products which _do_ include PIO in their source (e.g., ESMF) should do their own analysis.

I do think the COPYRIGHT should refer to a specific version of the GPL.

Disclaimer: IANAL

**Comment by climbfuji** [comment]
> I am not sure CESM's use of ParallelIO (PIO) violates the letter or spirit of the GPL license because CESM does not contain PIO. To use CESM, you need a PIO library but it is not included except by reference (i.e., no PIO code is copied into CESM or into any of its components).
> 
> Other products which _do_ include PIO in their source (e.g., ESMF) should do their own analysis.
> 
> I do think the COPYRIGHT should refer to a specific version of the GPL.
> 
> Disclaimer: IANAL

I spoke to someone today who said that by *linking* to a library under GPL you are bound to the license terms. But same here, I am not a lawyer ...

**Comment by gold2718** [comment]
> I spoke to someone today who said that by _linking_ to a library under GPL you are bound to the license terms. But same here, I am not a lawyer ...

Wouldn't that apply to any code compiled with gcc (gfortran)? That executable is linked with the GPL'd gcc runtime library.

Any lawyers out there?

**Comment by climbfuji** [comment]
I know, totally confusing to me ...

**Comment by climbfuji** [comment]
> > I spoke to someone today who said that by _linking_ to a library under GPL you are bound to the license terms. But same here, I am not a lawyer ...
> 
> Wouldn't that apply to any code compiled with gcc (gfortran)? That executable is linked with the GPL'd gcc runtime library.
> 
> Any lawyers out there?

At any rate, as far as I understand, the current license is an issue for anyone packaging PIO. That's not only ESMF, but also anyone who creates and releases a container or an Amazon Media Image or similar that contains PIO.

**Comment by briandobbins** [comment]
> Any lawyers out there?
>

  Michael Anderson in the UCAR Office of General Counsel has been
enormously helpful to me on numerous occasions involving license issues.
I'd recommend dropping him a note.

  - Brian

**Comment by climbfuji** [comment]
> Any lawyers out there?
> Michael Anderson in the UCAR Office of General Counsel has been enormously helpful to me on numerous occasions involving license issues. I'd recommend dropping him a note. - Brian
> […](#)

Will do so, thanks for the suggestion.

**Review by jedwards4b — APPROVED** [review]

**Review by edwardhartnett — APPROVED** [review]

**Comment by climbfuji** [comment]
Thanks everyone for your quick response to this, very much appreciated!

**Comment by edwardhartnett** [comment]
It's failing like this:

 ```
make -j distcheck
make  dist-gzip am__post_remove_distdir='@:'
make[1]: Entering directory '/home/runner/work/ParallelIO/ParallelIO'
make  distdir-am
make[2]: *** No rule to make target 'COPYRIGHT', needed by 'distdir-am'.  Stop.
make[2]: Entering directory '/home/runner/work/ParallelIO/ParallelIO'
make[2]: Leaving directory '/home/runner/work/ParallelIO/ParallelIO'
make[1]: Leaving directory '/home/runner/work/ParallelIO/ParallelIO'
make[1]: *** [Makefile:549: distdir] Error 2
make: *** [Makefile:651: dist] Error 2
Error: Process completed with exit code 2.

```
So you need to take the COPYRIGHT file out of the Makefile.am where it is included...

**Comment by climbfuji** [comment]
> It's failing like this:
> 
> ```
> make -j distcheck
> make  dist-gzip am__post_remove_distdir='@:'
> make[1]: Entering directory '/home/runner/work/ParallelIO/ParallelIO'
> make  distdir-am
> make[2]: *** No rule to make target 'COPYRIGHT', needed by 'distdir-am'.  Stop.
> make[2]: Entering directory '/home/runner/work/ParallelIO/ParallelIO'
> make[2]: Leaving directory '/home/runner/work/ParallelIO/ParallelIO'
> make[1]: Leaving directory '/home/runner/work/ParallelIO/ParallelIO'
> make[1]: *** [Makefile:549: distdir] Error 2
> make: *** [Makefile:651: dist] Error 2
> Error: Process completed with exit code 2.
> ```
> 
> So you need to take the COPYRIGHT file out of the Makefile.am where it is included...

Thanks ... I replaced COPYRIGHT with LICENSE in that file, let's see if that works.

**Comment by climbfuji** [comment]
Looks like it worked :-)

**Comment by climbfuji** [comment]
Thank you!

**Pull request merged**
