### PR TITLE
Hashtables

### PR DESCRIPTION
**Pull request by jedwards4b**
Convert several linked lists in PIO to hashtables using uthash from https://github.com/troydhanson/uthash
This will be a little slower for tests and small cases but will be much faster with large numbers of files/iodescs/variables/buffers

### CODE REVIEW

**Comment by edhartnett** [comment]
Wow, really neat! Have you tried any performance tests?

**Comment by jedwards4b** [comment]
I've just asked for the case in which they reported 40x speedup with pio1.  See issue #1339

**Comment by edhartnett** [comment]
@jedwards4b are we going to merge this?

**Comment by jedwards4b** [comment]
Not yet, I do want to get some performance numbers - I am working on it.

**Comment by edhartnett** [comment]
In order to pass the travis test you have to add your new header file to the list of source files in Makefile.am:

```
# The library soure files.
libpio_la_SOURCES = bget.c pioc_sc.c pio_darray.c pio_file.c		\
pio_getput_int.c pio_msg.c pio_nc.c pio_rearrange.c pioc.c		\
pioc_support.c pio_darray_int.c pio_get_nc.c pio_lists.c pio_nc4.c	\
pio_put_nc.c pio_spmd.c pio_internal.h bget.h
```

Just add it to the end of the list and commit the change...

**Comment by edhartnett** [comment]
OK, awesome! There's travis and you passed.

At the moment it only does the autotools based C library build. so make sure you check the other CI systems before merging this. ;-)

I will see about adding the cmake build, as well as some build variations like different versions of netcdf and pnetcdf...

**Comment by jedwards4b** [comment]
I've now merged this to develop for testing and plan to merge to master tomorrow am.

**Comment by jedwards4b** [comment]
@edhartnett I believe this is a false warning from codacy - are you okay to go ahead?

**Comment by edwardhartnett** [comment]
Yes, go ahead.

**Comment by jedwards4b** [comment]
I messed up the merge to develop yesterday - force pushed develop this morning to solve the issue.

**Pull request merged**
