### PR TITLE
fixed rec_var problem, this time I mean it.

### LINKED ISSUE #1136: Handle fixed-length time dimensions
In some existing input files of ESMCI/cime, the time dimension might have a fixed length. For example:
```
lat = 94 ;
lon = 192 ;
time = 12 ;
...
float prc(time, lat, lon) ;
```
Note: by definition, this kind of time dimension is NOT an unlimited dimension (a.k.a. record dimension). To support it, PR #1131 has removed rec_var check from setframe/advanceframe. This allows a frame number to be set even on non-record variables (with a fixed-length time dimension):
```
    /* Set the record dimension value for this variable. This will be
     * used by the write_darray functions. */
    vdesc->record = frame;
```
In PR #1088, ALL occurrences of "vdesc->record >= 0" have been replaced by "vdesc->rec_var".
However, for non-record variables with a fixed-length time dimension, it is possible that "vdesc->record >= 0" is true while "vdesc->rec_var" is false. With latest PIO2 master branch, some ESMCI/cime tests still fail due to this issue (confirmed).

For the write_darray functions, they should support writing both record variables (with an unlimited time dimension) and non-record variables (with a fixed-length time dimension). We should probably revert testing of "vdesc->rec_var" back to "vdesc->record >= 0" (partially revert PR #1088).

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #1136.

I have merged to develop for testing.

### CODE REVIEW

**Comment by dqwu** [comment]
@edhartnett 
In pio_darray_int.c, line 986 we have
```
pioassert((fndims == ndims && !vdesc->rec_var) ||
          (fndims == ndims + 1 && vdesc->rec_var),
          "invalid rec_var", __FILE__, __LINE__);
```
Here, do we need to replace "!vdesc->rec_var" to "vdesc->record < 0" and "vdesc->rec_var" to "vdesc->record >= 0"?

**Comment by dqwu** [comment]
For now, PR #1138 has caused develop branch to fail during build stage for CDash.
I will manually check this fix with all PIO unit tests and cime_developer tests.

**Comment by edhartnett** [comment]
@dqwu I agree that pioassert should be removed.

Apparently this code is not called in our tests yet.

I am going to delete the assert and commit the changes.

**Comment by edhartnett** [comment]
Unfortunately pio_decomp_frame_tests is still failing on develop. I will take a look at it some more tomorrow morning. Until it's sorted out I won't merge this PR.

**Comment by dqwu** [comment]
@edhartnett 
I noticed that the 2nd commit https://github.com/NCAR/ParallelIO/pull/1139/commits/2ae790d in this PR not only removed the assert, but also unexpectedly reverted some changes from the 1st commit https://github.com/NCAR/ParallelIO/pull/1139/commits/e301cc0. You need to reapply the changes made in the 1st commit.

PS, that pioassert should not be removed, as it is actually covered by pio_decomp_frame_tests. Of course the original assert would fail (as expected) for test nc_test_limited_time_dim (a new Fortran test added to pio_decomp_frame_tests). We can update the original assert to a new one like below:
/* Confirm record setting. */
pioassert((fndims == ndims && vdesc->record < 0) ||
          (fndims == ndims + 1 && vdesc->record >= 0),
          "unexpected record", __FILE__, __LINE__);

**Comment by dqwu** [comment]
@edhartnett 
FYI, the GCOV report shows that the removed pioassert is hit many times in the code. It is also covered by some C tests like test_pioc and test_darray.
```
985                 :            :     /* Confirm rec_var setting. */
986 [ +  + ][ -  + ]:      27748 :     pioassert((fndims == ndims && !vdesc->rec_var) ||
            [ +  - ]
987         [ +  - ]:       5176 :               (fndims == ndims + 1 && vdesc->rec_var),
988                 :            :               "invalid rec_var", __FILE__, __LINE__);
```

**Comment by edhartnett** [comment]
OK, I cleaned up to try and reduce the complexity here.

I have merged my other large outstanding PR, with the autotools build system. I then re-created develop, and started with a new branch of master. I have reapplied my rec_var changes carefully to this new branch. 

It is passing all tests, but I have not yet tried with @dqwu's new test.

**Comment by dqwu** [comment]
@edhartnett 
So you will close this PR and recreate a new PR with ejh_recvar_3?
I have checked branch ejh_recvar_3, there are some issues:
1) In pio_darray_int.c, line 388, "vdesc->rec_var" should be "vdesc->record >= 0"
line 226 and 285, "vdesc->record >= 1" should be "vdesc->record >= 0"
2) In line 985 of pio_darray_int.c, the comment "Confirm rec_var setting" might need to be updated, as the assert is now checking vdesc->record, not vdesc->rec_var
3) This branch merged the new Fortran test. It is OK for local testing, but that test should be merged to master by PR #1137

Since the develop branch has been re-created, I will re-merge PR #1137 to the new develop branch.

You can create another branch (say ejh_recvar_4), without merging the Fortran test, and fix the issues above, then create a new PR (also close this PR) and merge it to develop. Thanks.

**Comment by edhartnett** [comment]
Yes, I will take this PR down.

Thanks for the feedback, I am working on ejh_recvar_3 now.

**Comment by dqwu** [comment]
@edhartnett 
Latest ejh_recvar_3 looks OK, thanks.

Could you please also update the comment in line 985 of pio_darray_int.c? 

To avoid duplicate merge of the new Fortran test to master (PR #1133 will merge it) and keep the commit history to master clean, it is better to create a new branch (almost the same as ejh_recvar_3, but there is no merge of the Fortran test) to submit a new PR, thoughts?

**Pull request closed without merging**
