### PR TITLE
changed version to 2.5.5

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #1884 

Updating versions for next release.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@jedwards4b are we closing in on a release?

**Comment by jedwards4b** [comment]
I am working on a refactor of rearrange methods that will reduce the memory footprint, I would like to complete this today.

**Comment by edwardhartnett** [comment]
OK, no rush. Let me know when you are ready...

**Comment by edwardhartnett** [comment]
Converting this PR to draft until we clear off some of the issues related to the next release...

**Comment by jedwards4b** [comment]
Are we ready to merge this?

**Comment by edwardhartnett** [comment]
No I need to fix the dispatch table. I'm going to do that tomorrow - the
rest of today is booked up...

**Comment by jedwards4b** [comment]
Sounds good, thanks.

**Review by jedwards4b — APPROVED** [review]

**Comment by edwardhartnett** [comment]
Stuck on a documentation problem... Stand by...

**Pull request merged**
