### PR TITLE
adding cmake build, fix code warnings

### LINKED ISSUE #1728: cmake build on github needs to build fortran too
Seems like the fortran build on the cmake github workflow is not being built, but it needs to be.

### LINKED ISSUE #1838: code warnings in netcdf-integration build
```
tst_var_compress.c: In function ‘run_var_compress_test’:
tst_var_compress.c:77:13: warning: unused variable ‘ret’ [-Wunused-variable]
   77 |         int ret;
      |             ^~~
tst_var_compress.c:72:30: warning: unused variable ‘deflate_level_in’ [-Wunused-variable]
   72 |  int shuffle_in, deflate_in, deflate_level_in, storage_in;
      |                              ^~~~~~~~~~~~~~~~
tst_var_compress.c:72:18: warning: unused variable ‘deflate_in’ [-Wunused-variable]
   72 |  int shuffle_in, deflate_in, deflate_level_in, storage_in;
      |                  ^~~~~~~~~~
tst_var_compress.c:72:6: warning: unused variable ‘shuffle_in’ [-Wunused-variable]
   72 |  int shuffle_in, deflate_in, deflate_level_in, storage_in;
      |      ^~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #1728

Added a new cmake build workflow which builds dependent libraries.

Fixes #1838 

Fixed some code warnings.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@jedwards4b I have added a cmake build. As you can see it is failing with the big-endian problem. I have added cmake to the list of apt-get packages.

**Comment by jedwards4b** [comment]
Can you remind me how to view logs?
See also "/home/runner/work/ParallelIO/ParallelIO/b1/CMakeFiles/CMakeOutput.log".
See also "/home/runner/work/ParallelIO/ParallelIO/b1/CMakeFiles/CMakeError.log".

**Comment by edwardhartnett** [comment]
There is no way to view logs. ;-)

**Comment by jedwards4b** [comment]
Yes there is, I've done it before - you can actually log into the server - I've done it before but need to figure it out again.

**Comment by jedwards4b** [comment]
https://github.com/marketplace/actions/debugging-with-tmate

**Review by edwardhartnett — COMMENTED** [review]
Ahha!

**Pull request merged**
