### PR TITLE
Box optimization

### PR DESCRIPTION
**Pull request by jedwards4b**
Cherry-pick some of the optimizations from the e3sm fork.

### CODE REVIEW

**Comment by edhartnett** [comment]
OK, how about we take this a little bit at a time? Let us first sort out the memory issues on master, which I cannot reproduce.

I have just put up a branch which changes the default cmake memory use to malloc instead of bget.

**Comment by jedwards4b** [comment]
I'm confused by your reference to memory issues - the failures above seem to be due to mpi getting out of sync between comp and io tasks.

**Comment by jedwards4b** [comment]
@edhartnett I have rebased this to master after PR #1391 - will you review now?

**Comment by edhartnett** [comment]
@jedwards4b should we merge these?

**Comment by jedwards4b** [comment]
Yes

**Pull request merged**
