### PR TITLE
wrote up code review

### PR DESCRIPTION
**Pull request by edhartnett**

### CODE REVIEW

**Comment by rljacob** [comment]
Pull requests will only be merged on work days.

**Comment by rljacob** [comment]
Or, at least one working day will be allowed between submission and fulfillment of the pull request.  I don't like PRs going in on weekends, holidays.  That's unfair to developers who really need to take time off.

**Comment by gold2718** [comment]
I have questions about this document. First, it says:

> Pull requests will be left up on github for about a day. 

Was this pull request up for "about a day"?
The doc also says: 

> All non-trivial pull requests are associated with a github issue

As this pull request affects all future pull requests, it does not seem trivial to me. Is there an issue for this pull request? I would think that something triggered a change of procedure -- this should be discussed in a github issue (per the document) before submitting a pull request.

**Comment by edhartnett** [comment]
@rljacob we are happy to wait for all interested programmers. We can wait for workdays only, if that would help.

@gold2718 welcome to the discussion! ;-) I have opened a github issue for this #261 if anyone would like  a place to comment.

**Pull request merged**
