### PR TITLE
switch cmake build to use malloc not bget by default

### PR DESCRIPTION
**Pull request by edhartnett**
Attempting to sort out memory issues before making other changes...

### CODE REVIEW

**Comment by jedwards4b** [comment]
The reason these tests fail with malloc but not bget - is that they are not implemented with bget.  
See tests/cunit/CMakelists.txt line 95

**Comment by edhartnett** [comment]
OK, sorry for the confusion.

But in any case, I can't reproduce these. And we can see from the travis build of this branch, the autotools and cmake builds are both run.

Also I have a jenkins matrix that runs for all combinations of 3 netcdf and 2 pnetcdf versions. And everything is passing.

Perhaps the problem is intermittent?

**Comment by jedwards4b** [comment]
I can reproduce the problem consistently, but it is intermittent in that it tends to be the second comp task which is left behind, but occasionally its the first comp task.

**Comment by edhartnett** [comment]
I will take this PR down since this change is in PR #1391 as well.

**Pull request closed without merging**
