### PR TITLE
took out ncid, fixed memory leak

### LINKED ISSUE #681: 21 Fortran tests failed memory leak check
This issue is caused by PR #680, which is reproducible in both develop and master branches.

[Root cause of the leaks]
In flush_buffer(), pio_darray_int.c, the code is updated by the PR such that if PIOc_write_darray_multi() returns an error, flush_buffer() will return that error, without executing the following clean up code.
```
/* If there are any variables in this buffer... */
if (wmb->validvars > 0)
{
    /* Write any data in the buffer. */
    if ((ret = PIOc_write_darray_multi(ncid, wmb->vid,  wmb->ioid, wmb->validvars,
                                       wmb->arraylen, wmb->data, wmb->frame,
                                       wmb->fillvalue, flushtodisk)))
        return pio_err(NULL, file, ret, __FILE__, __LINE__);

    wmb->validvars = 0;

    /* Release the list of variable IDs. */
    brel(wmb->vid);
    wmb->vid = NULL;
    ...
}
```

[Code that triggers the leaks]
On the other hand, in PIOc_write_darray_multi(), pio_darray.c, the code is updated by the PR to check returned value from flush_output_buffer(). For the 21 failed Fortran tests, flush_output_buffer() does return an error code (e.g. PIO_EBADID), which is then returned by PIOc_write_darray_multi().
```
/* Flush data to disk. */
if (file->iotype == PIO_IOTYPE_PNETCDF)
    if ((ierr = flush_output_buffer(file, flushtodisk, 0)))
        return pio_err(ios, file, ierr, __FILE__, __LINE__);
```

[How to fix]
We should make sure that the clean up code is executed even if PIOc_write_darray_multi() fails.

### PR DESCRIPTION
**Pull request by edhartnett**
Part of #672.
Fixes #681

### CODE REVIEW

**Comment by jayeshkrishna** [comment]
Did taking out the ncid fix the memory leak?

**Comment by edhartnett** [comment]
Nope, but taking out the ncid was something I had just completed, so I just fixed the memory leak and put my branch up for review.

**Comment by dqwu** [comment]
Next time it would be better to use two PRs, one for taking out the ncid, and one for fixing memory leaks. Try to let each PR make minimal code changes.

**Comment by jayeshkrishna** [comment]
I cannot figure it out from the commit messages (it would be good to have separate commits and detailed commit messages so that it is clear how/what bugs got fixed).
I defer the review to @jedwards4b

**Comment by edhartnett** [comment]
You really can't figure out what is going on in this code? Or you are just enjoying busting on me? 

I will close this PR and break this into two PRs, and you take a look and try again.

**Comment by jayeshkrishna** [comment]
From a quick look I could not figure it out. But if @jedwards is ok with it I am fine too (you don't have to recreate it if @jedwards is ok with it).

**Comment by edhartnett** [comment]
@jayeshkrishna, @dqwu,  I welcome your comments on my code.

What I would like to see is the same interest in following process rules, we all also have for reviewing code and making comments. 

We all want this library to contain the highest quality code, so I invite you all to study the code, get to know it, and point out where it can be improved by removing unneeded complexity, adding documentation, changing variable names to be more clear, etc. And, of course, by finding bugs. ;-)

Thanks,
Ed

**Pull request closed without merging**
