### PR TITLE
test development

### LINKED ISSUE #727: Tests for darray with non-default rearranger
All current C tests for darray use the default rearranger.

### LINKED ISSUE #741: Add unlimited dim tests to test_darray_1d.c
Currently tests with 1 fixed dim. Add a test with a fixed dim + unlimited dim.

### LINKED ISSUE #749: test_darray_1d failed on develop branch
With PR #744 merged to develop branch, test_darray_1d failed AddressSanitizer check:
http://my.cdash.org/testDetails.php?test=30132945&build=1144283

Please fix this issue before merge the PR to master.

### PR DESCRIPTION
**Pull request by edhartnett**
Added tests to test_darray_1d.c.

No library changes in this PR, just test code.

This test led to issue #743. The test has been modified to avoid that test case pending solving that issue.

I will merge to develop for testing.

Fixes #741.
Fixes #727.
Fixes #749.
Part of #205.

### CODE REVIEW

**Comment by jedwards4b** [comment]
I think that I see the problem in this test.   The calls to pio_write_darray_multi_nc(_serial)
at lines 231 and 239 of pio_darray.c use iodesc->holegridsize as the argument for maxiobuflen

maxiobuflen should be the max value of holegridsize across all tasks.

**Comment by edhartnett** [comment]
OK, I am going to merge this test to master, then do a fix on a new branch.

**Comment by jayeshkrishna** [comment]
I thought we discussed that the test (that shows a problem) and the fix go in the same PR/branch.

**Comment by edhartnett** [comment]
@jayeshkrishna thanks for explaining your thought processes. Is there a question there?

**Comment by edhartnett** [comment]
@jedwards4b is it possible that the problem is just above the :pio_write_darray_multi_nc call:

```
        /* Get a buffer. */
        vdesc0->fillbuf = bget(iodesc->holegridsize * vsize * nvars);
```

When I traced through the code, it seemed that in the failing process, this bget resulted in 0 for the processes that crashed, and latter a fill value was attempted to be written there.

**Comment by jedwards4b** [comment]
Yes, we shouldn't be calling bget if holegridsize=0

**Comment by jedwards4b** [comment]
From an earlier comment:
 > maxiobuflen should be the max value of holegridsize across all tasks.

This is incorrect - maxiobuflen is the max length across io tasks in an io_comm but subset rearranger only has 1 io task per io comm and so holegridsize is correct.

**Comment by edhartnett** [comment]
Can you put that explanation in the code as a comment?

**Comment by dqwu** [comment]
There is another issue found. The develop branch failed AddressSanitizer check (on test_darray_1d) after this PR was merged. More information, see http://my.cdash.org/testDetails.php?test=30131815&build=1144243

**Comment by edhartnett** [comment]
@dqwu I know what that is and can fix it. @jedwards4b please let me know when your fix for the subset rearranger problem is merged and I will fix this memory issue.

**Comment by jayeshkrishna** [comment]
@edhartnett : Will the test that exposes the issue be merged to master before a fix for it? What we had discussed before was that the fix goes along with the test that shows the issue (same branch, same PR).

**Comment by edhartnett** [comment]
@jayeshkrishna have you reviewed the code in the PR?

**Comment by jayeshkrishna** [comment]
No I haven't. It would be great if @jedwards4b reviews this PR.

**Comment by dqwu** [comment]
@jedwards4b 
Since you just pushed a new commit to this PR, could you please merge it to the develop branch?

**Comment by jedwards4b** [comment]
Yes, working on it

**Comment by jedwards4b** [comment]
merged to develop

**Comment by dqwu** [comment]
@edhartnett 
Could you please fix issue #749 before merging this PR to master (add new commits to fix)? Thanks.

**Comment by jedwards4b** [comment]
Sure I would love to - how?   I'm not getting much useful out of that valgrind output, are you?

**Comment by edhartnett** [comment]
I can fix that one, but I can't get Jim's fix to work for me...

**Comment by edhartnett** [comment]
I have fixed the memory issue.

Let's get these changes merged and then circle back around to solve the PIO_DOUBLE/PIO_REARR_SUBSET issue. All the other test combinations pass and add value to our testing.

**Comment by edhartnett** [comment]
@jayeshkrishna I do not recall the discussion that you cite. Certainly tests that find bugs can be developed and committed before the bug fix is found. As long as a github issue is started for each issue, then feel free to comment out the part of the test that fails, and commit the rest. I do this occasionally.

While I can sometimes find the bug as I go, other times I can't, but I still want to capture the good tests that are working and test functionality that is working fine. So I create an issue for the bug, and continue moving forward.

For example, yesterdays merge of test_darray_1d.c code allows me to easily continue working on my darray/fill value issues, while Jim and I also figure out why his fix from yesterday is not working for me. This allows me to complete and submit multiple pull requests every day.

Having a good software quality process gives us the opportunity to inspect and comment on changes. If we don't take advantage of that opportunity to improve code quality, then even a perfect process will not help.

**Comment by jayeshkrishna** [comment]
@edhartnett : Please see #265

**Comment by edhartnett** [comment]
@jayeshkrishna please re-read that ticket. What is says is that you can't check in a failing test. What we are discussing here is commenting out test code so that the test can pass while the issue is resolved. 

In the case of a failing test, it breaks the CI system(s), in the case of a commented out test, it does not break the CI system and all other tests continue to perform their required function. So in the first case, team development stops, and in the second case, it can continue.

Therefore it is perfectly OK to comment out test code while you work on fixes (and you have a github issue so it does not get forgotten), but it is not OK to merge test code that fails, and break the CI builds. Because then the other developers on the project do not have the benefit of all those working tests running under the CI system.

None of these rules come from me - they are just standard agile development practice.

**Comment by rljacob** [comment]
We've had this conversation before.  A "global PASS" is just how you do CI, Ed.  The dashboard is quite capable of separating individual passes and fails.  Failing test are allowed because they show what needs to be fixed more capably then an open github issue.  You never comment out a test because its to easy to forget to un-comment it.

**Comment by rljacob** [comment]
There's tons of material on the web about agile development.  If you can find a good reference about how one should always comment out failing tests then we'll believe that is "standard agile development practice".

**Comment by edhartnett** [comment]
How about here:
https://github.com/Unidata/netcdf-c/blob/master/CONTRIBUTING.md

**Comment by rljacob** [comment]
Didn't you work on NetCDF before?  That's probably where this odd practice started.  So I'd like a different source.  Even so, those instructions don't say all tests must pass or be commented out and the Travis board for NetCDF has failing tests on it.

**Pull request merged**
