### PR TITLE
added tests for ceil2() and pair() function in pio_spmd.c

### LINKED ISSUE #636: Test for ceil2() and pair() functions in pio_spmd.c
These functions are currently untested.

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #636. Part of #205.

Generated issues #645 and #646, but we can merge these working tests, which test the actual functionality of these functions. If we find that needs to change, the tests can change with it.

I will merge to develop for testing.

### CODE REVIEW

**Comment by jayeshkrishna** [comment]
Do these tests pass?

**Comment by jayeshkrishna** [comment]
And a question for everyone ( @jedwards4b / @edhartnett / @Katetc / @dqwu ) do we merge to develop before or after the review (refreshing my memory on the process)?

**Comment by edhartnett** [comment]
These tests pass or I would not have merged them to develop. ;-)

**Comment by edhartnett** [comment]
@jayeshkrishna although you will be adding tests, I would like to keep these tests as well.

My understanding is that your tests will be in fortran. I would also like to have C tests covering all the C code. So although something may be tested in fortran, I would still like to keep C tests.

**Comment by jayeshkrishna** [comment]
I won't be removing any tests.

**Pull request merged**
