### PR TITLE
Recvar fixes

### LINKED ISSUE #1136: Handle fixed-length time dimensions
In some existing input files of ESMCI/cime, the time dimension might have a fixed length. For example:
```
lat = 94 ;
lon = 192 ;
time = 12 ;
...
float prc(time, lat, lon) ;
```
Note: by definition, this kind of time dimension is NOT an unlimited dimension (a.k.a. record dimension). To support it, PR #1131 has removed rec_var check from setframe/advanceframe. This allows a frame number to be set even on non-record variables (with a fixed-length time dimension):
```
    /* Set the record dimension value for this variable. This will be
     * used by the write_darray functions. */
    vdesc->record = frame;
```
In PR #1088, ALL occurrences of "vdesc->record >= 0" have been replaced by "vdesc->rec_var".
However, for non-record variables with a fixed-length time dimension, it is possible that "vdesc->record >= 0" is true while "vdesc->rec_var" is false. With latest PIO2 master branch, some ESMCI/cime tests still fail due to this issue (confirmed).

For the write_darray functions, they should support writing both record variables (with an unlimited time dimension) and non-record variables (with a fixed-length time dimension). We should probably revert testing of "vdesc->rec_var" back to "vdesc->record >= 0" (partially revert PR #1088).

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #1136.

These changes pass the new test in pio_decomp_frame_tests.

I have merged to develop for testing.

### CODE REVIEW

**Comment by dqwu** [comment]
@edhartnett 
Looks OK. The only concern is that the 1st and the 7th commits will complicate the commit history to master (VS PR #1137). 

When this PR is merged to develop, it will delete the Fortran test previously merged that branch (then we have to merge it to develop again).

My suggestion is: you can create a new branch, git cherry-pick 2nd to 6th commits from ejh_recvar_3, and resubmit a PR.

**Comment by dqwu** [comment]
@edhartnett 
It is better to have a new branch and a new PR. Another known issue is: If PR #1137 is merged to master first, then merging of this PR to master will revert the new Fortran test.

**Comment by edhartnett** [comment]
I am going to merge these PRs, as the dash testing is showing a failure, and these PRs will fix it.

**Comment by edhartnett** [comment]
I have merged everything, and I think it all came out OK. The new fortran test is where it should be on master. I am running all my Jenkins jobs now...

**Comment by dqwu** [comment]
@edhartnett 
The new Fortran test is in master, but it is no longer in develop. I need to re-merge it.

**Comment by dqwu** [comment]
@edhartnett 
I think you need to recreate the develop branch again. The Fortran test is lost in it now and I cannot merge the feature branch as it has been already merged before.

**Pull request merged**
