### PR TITLE
Adding more 1d Fortran tests

### PR DESCRIPTION
**Pull request by jayeshkrishna**
Adding more 1d fortran tests,
* More combinations that force data rearrangement during read and write tested
* Testing reusing iodescs across reads (and reads+writes)

### CODE REVIEW

**Comment by edhartnett** [comment]
Does this test check all different data types?

It looks to me like the malloc_iodesc function incorrectly sets the basetype for types < 4 bytes in size (i.e. shorts and chars). I believe that the only result is that later, too much memory is allocated to hold the data.

**Comment by jayeshkrishna** [comment]
This test should test INTEGER, REAL (float/double) types. The fortran tests currently don't test other data types (types supported in netcdf that were added to pio)

**Comment by jayeshkrishna** [comment]
Merged to develop - b4f89218ce8b5cddfe92f4119dbc9fa2a971f8b5

**Comment by edhartnett** [comment]
Would you like me to merge this to master, or are you still working on these tests? Thanks!

**Comment by jedwards4b** [comment]
Do not merge yet,  this is failing with multiple compiler errors on nag which has a hard line length limit of 132 characters.   It appears that the preprocessor is putting a comment at the end of each line of the F90 file with the line number from the original source.  This is unnecessary - if you use the cpp line control information you will get something that compilers can use to reference the correct source line.   
https://gcc.gnu.org/onlinedocs/cpp/Line-Control.html#Line-Control

**Comment by jayeshkrishna** [comment]
I will try to see if I can get the line length less than 132 characters.
I have always had issues debugging code that has line control information in them. I think the testing framework has option to use line control if needed.

**Comment by jayeshkrishna** [comment]
The line lengths should now be under 132 chars (I verified manually) and I have re-merged the change to develop.

**Comment by jayeshkrishna** [comment]
The cdash results look good. Merging it to master now.

**Pull request merged**
